# Numpy exercises

## Import numpy

* Import the numpy module with the standard shorthand np

In [1]:
import numpy as np

## Creating numpy objects

* Create a numpy 1D array containing the numbers
```
[0, 1, 2, ... 10]
```

In [2]:
np.arange(11) # last index excluded

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

* Create a numpy 1D array containing the numbers
```
[1, 2, 3, ... 10]
```

In [3]:
np.arange(1, 11) # first index included, last index excluded

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

* Create a 3x2 matrix (i.e. 2D array) with elements

``` 
[[1.0, 2.0], 
 [4.0, 5.0],
 [2.0, 3.0]]
```

In [4]:
np.array([[1.0, 2.0], [4.0, 5.0], [2.0, 3.0]])

array([[1., 2.],
       [4., 5.],
       [2., 3.]])

* Create a 3x4 matrix containing random values with a standard Gaussian distribution

In [5]:
np.random.randn(3, 4)

array([[-0.22031734, -1.87428277,  1.20417402, -0.81781309],
       [-0.03641638, -0.21036444, -0.18861038,  0.77759474],
       [-0.26796142, -0.3936573 , -1.03988436,  0.34527982]])

* Create a 4x3 matrix containing random values with a uniform distribution in $[0, 1)$

In [6]:
np.random.rand(4,3)

array([[0.6355062 , 0.18412993, 0.44816747],
       [0.39792377, 0.17332205, 0.46783366],
       [0.42070732, 0.2559862 , 0.62108339],
       [0.53832205, 0.70881501, 0.11170384]])

* Create a 4x4 matrix of type np.int64 containing the value 42 on all the elements:


In [7]:
42*np.ones((4, 4), dtype=np.int64)  #or np.full((4,4), fill_value=42, dtype=np.int64)

array([[42, 42, 42, 42],
       [42, 42, 42, 42],
       [42, 42, 42, 42],
       [42, 42, 42, 42]])

## Processing

* Create a 1D numpy array called ``phase`` containing 100 points in the numerical range $[0, 2\pi]$

In [8]:
phase = np.linspace(0, 2*np.pi, 100)

* Compute the sin and the cos of ``phase`` using numpy

In [9]:
sin_phase = np.sin(phase)
cos_phase = np.cos(phase)

*  Compute a new 1D array called ``phase2`` defined as ``phase`` + $\pi$

In [10]:
phase2 = phase + np.pi

* Compute sin and cos of phase2. What do you notice? What did you expect?

In [11]:
sin_phase2 = np.sin(phase2)
cos_phase2 = np.cos(phase2)

In [12]:
np.max(np.abs(sin_phase + sin_phase2)) # sin_phase2 is (almost) equal to - sin_phase. 

9.43689570931383e-16

In [13]:
np.allclose(sin_phase, -sin_phase2) # check for numerically significant difference.

True

Note: in theory, $sin(x) = -sin(x + \pi$). The difference between sin_phase and sin_phase2 is just a small numerical error

## Linear algebra
* construct the canonical base $\{\overrightarrow {e_1}, \overrightarrow {e_2}, \overrightarrow {e_3}\}$ of $\mathbb{R}^3$ as 1D numpy arrays

In [14]:
# Canonical base of R^3. Note: e1, e2, e3 are 1D arrays, with 3 elements.
e1 = np.array([1, 0, 0]) 
e2 = np.array([0, 1, 0])
e3 = np.array([0, 0, 1])

* Compute the dot products: $ \overrightarrow {e_1} \cdot \overrightarrow {e_2}$ and $ \overrightarrow {e_3} \cdot \overrightarrow {e_3}$

In [15]:
np.dot(e1,e2)

0

In [16]:
np.dot(e3,e3)

1

* Compute the cross product: $ \overrightarrow {e_2} \times \overrightarrow {e_3}$

In [17]:
np.cross(e2, e3)

array([1, 0, 0])

* Compute $(3 \overrightarrow {e_2} - 2 \overrightarrow {e_3}) \cdot (3 \overrightarrow {e_2} + \overrightarrow {e_3} - 2\overrightarrow{e_2})$

In [18]:
np.dot(3*e2 - 2*e3, 3*e2 + e3 -2*e2)

1

* Compute $(3 \overrightarrow {e_2} - 2 \overrightarrow {e_3}) \times (3 \overrightarrow {e_2} + \overrightarrow {e_3} - 2\overrightarrow{e_2})$

In [19]:
np.cross(3*e2 - 2*e3, 3*e2 + e3 -2*e2)

array([5, 0, 0])

## Aggregations

* Create a 4x2 matrix (i.e. 2D array) called `A` with elements

``` 
[[1.0, 2.0], 
 [4.0, 5.0],
 [1.0, 3.0],
 [4.0, 1.0]
```

In [20]:
A = np.array([[1.0, 2.0], [4.0, 5.0], [1.0, 3.0], [4.0, 1.0]])
A

array([[1., 2.],
       [4., 5.],
       [1., 3.],
       [4., 1.]])

* Compute the sum of all the elements of A

In [21]:
np.sum(A)

21.0

* Compute the sum of the elements of the columns of A

In [22]:
np.sum(A, axis=0)

array([10., 11.])

* Compute the sum of the elements of the rows of A

In [23]:
np.sum(A, axis=1)

array([3., 9., 4., 5.])

## Indexing & Slicing

* Create a matrix ``B`` of size 4x3 containing random values from the standard Gaussian distribution

In [24]:
B = np.random.randn(4, 3)
B

array([[ 1.3908763 , -0.62036657,  0.04708101],
       [-0.05570993, -0.93618285, -0.41109679],
       [ 0.19890574, -0.05446604,  0.72376021],
       [ 0.43035158,  1.39760711,  0.09462083]])

1. Select the element in position (2, 2)

In [25]:
B[2, 2]

0.7237602059710981

* Select the first row of ``B``

In [26]:
B[0, :]

array([ 1.3908763 , -0.62036657,  0.04708101])

* Select the second column of ``B``

In [27]:
B[1, :]

array([-0.05570993, -0.93618285, -0.41109679])

* Select a portion of ``B`` corresponding to the intersection of the first 2 rows and the first 2 columns

In [28]:
B[0:2, 0:2] # or B[:2, :2]

array([[ 1.3908763 , -0.62036657],
       [-0.05570993, -0.93618285]])

* Replace the values of ``B`` greater than 1 to 1

In [29]:
B[B>1] = 1
B

array([[ 1.        , -0.62036657,  0.04708101],
       [-0.05570993, -0.93618285, -0.41109679],
       [ 0.19890574, -0.05446604,  0.72376021],
       [ 0.43035158,  1.        ,  0.09462083]])

* Replace the values of ``B`` smaller than -1 to -1

In [30]:
B[B<-1] = -1