# Numpy: Numerical Python

<!-- ## Marco Forgione -->




The workhorse of numerical mathematics and machine learning in Python


## Data challenge module: evaluation


Grades are based on a **presentation** to be prepared using the jupyter/python environment. You will put in practice the data cleanup, preparation, visualization, and analysis techniques discussed in this course **on a dataset of your choice**.

* You will work in **groups of 2** (exceptions to be agreed with the teacher).
* An **excel sheet** is on the Data challenge team on MS Teams. Fill it in with the name/surname of the group members **by March 28**.
* During **the last 2 lectures** of the Data Challenge module, each group will deliver a 10-minute talk followed by a 5-minute Q&A session.
* Group presentation order will be **randomly extracted**. 
* In general, the members of a group will receive **the same grade**.
* If the group members eventually prefer to be graded separately, they should communicate their decision as soon as possible, prepare substantially different works, and deliver separate talks.

## Recap

In the previous lecture:

* We discussed the overall objective of the data challenge module
* We introduced Jupyter notebook
* We reviewed some Python basics



Today, we introduce one of the most important libraries for scientific computation in Python: **numpy**.

## Numpy in a nutshell

Provides data structures & algorithms for numerical mathematics needed in most scientific applications in Python

* An efficient multidimensional array: ```ndarray```
* Function performing mathematical operations on arrays
* Linear algebra, Fourier transform, ...
* Fast  *vectorized* array operations

## Getting started with numpy

Let us import the ``numpy`` module and give it the shorthand name ``np``. This is a standard convention!

In [1]:
import numpy as np

In [2]:
# Let us define some arrays
x1 = np.random.randint(10, size=6)  # One-dimensional array (aka vector)
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array (aka matrix)

In [3]:
type(x1), type(x2)

(numpy.ndarray, numpy.ndarray)

In [4]:
x1 # a 1D numpy array ("vector")

array([8, 5, 2, 7, 5, 5])

In [5]:
x2 # a matrix ("matrix")

array([[3, 9, 7, 0],
       [2, 3, 7, 3],
       [1, 5, 7, 0]])

In *Linear Algebra* you have called the 1D array **vector**. You will call the 2D array **matrix**.

##  Why numpy?

In principle, we can implement math operations in plain Python (using the ``math`` module):

In [6]:
import math

x_list = [math.sin(x) for x in range(100000)] # math operation in plain python

Same operation in ``numpy``:

In [7]:
x_np = np.sin(np.arange(100000)) # same math operation in numpy 

In [8]:
x_list == x_np # numerical result is the same

array([ True,  True,  True, ...,  True,  True,  True])

The result is the same, but performance changes dramatically!

In [9]:
%timeit -n 50 x_list = [math.sin(x) for x in range(100000)] # execute the statement 50 times to check execution time

15.1 ms ± 539 µs per loop (mean ± std. dev. of 7 runs, 50 loops each)


In [10]:
%timeit -n 50 x_np = np.sin(np.arange(100000))

1.79 ms ± 71.4 µs per loop (mean ± std. dev. of 7 runs, 50 loops each)


* The numpy ndarray is *optimized* for fast mathematical operations on large amounts homogeneous (same-type) data
* Under the hood, efficient  numerical routines are used in numpy (C/FORTRAN compiled code).
* Conversely, the python list support generic python objects. It is more flexible, but far slower.
* Using numpy, we get (almost) the performance of a compiled language, with the flexibility of an interpreted language!

### Array attributes:

The ``ndarray`` object has the following useful attributes:

* ndim, **shape**, size
* **dtype**, itemsize, nbytes

In [11]:
x3 = np.random.randint(10, size=(5, 4, 5))  # Three-dimensional array

In [12]:
# Useful attributes about array dimensions
print(f"x3.ndim:  {x3.ndim}")   # 3: x3 is a 3D array
print(f"x3.shape: {x3.shape}")  # (3, 4, 5)
print(f"x3.size:  {x3.size}")   # 100: x3 contains 5 x 4 x 5 elements

x3.ndim:  3
x3.shape: (5, 4, 5)
x3.size:  100


In [13]:
# Useful attributes about array data type
print(f"x3 dtype: {x3.dtype}")    # x3 is a 64-bit integer
print(f"x3 itemsize (bytes): {x3.itemsize}") # A 64-bit integer occupies 8 bytes
print(f"x3 nbytes: {x3.nbytes}") # 5 x 4 x 5 x 8 = 800 bytes

x3 dtype: int64
x3 itemsize (bytes): 8
x3 nbytes: 800


## 2D array, a.k.a. matrix

It is fairly common to work with 2D arrays. They are equivalent to matrices in linear algebra!

In [14]:
# build a numpy array from a list of lists.
import numpy as np
A = np.array([[1.0, 2.0, 3.0], 
              [6.0, 5.0, 4.0]], dtype=np.float32) 
A

array([[1., 2., 3.],
       [6., 5., 4.]], dtype=float32)

In [15]:
A.ndim

2

In [16]:
A.shape # A has two dimension. The innermost dimension # rows is 2, the outer dimension #n_cols is 3

(2, 3)

In [17]:
A.dtype

dtype('float32')

A really basic operation: add 1 to all the elements of matrix A

In [18]:
A+1

array([[2., 3., 4.],
       [7., 6., 5.]], dtype=float32)

You will learn more about matrix computation in the *Linear Algebra* module. 

Any kind of matrix computation (inverse, matrix multiplication, eigenvalues, eigenvectors, ...) is natively supported in ``numpy``.

# 1D array,  a.k.a. vector 

1D numpy arrays may be seen as vectors, as you probably know from linear algebra

In [19]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In Linear Algebra, there is a distinction between row- and column-vectors.
Is ``x`` a row or a column vector? In fact, this is not even specified!

In [20]:
# A vector (neither row nor column)
x.shape # x has only one dimension. It has length 4.

(4,)

To construct row/column vectors, we use 2D numpy arrays

In [21]:
# A row vector

x_row = np.array([[1, 2, 3, 4]])
x_row.shape

(1, 4)

In [22]:
# A column vector

x_col = np.array([[1], [2], [3], [4]])
x_col.shape

(4, 1)

# Common constructors

How do we define a numpy array?

In [23]:
# From a list of numeric values
np.array([3.14, 6.24, 2.71], dtype=np.float32) # can also specity the data type

array([3.14, 6.24, 2.71], dtype=float32)

In [24]:
# From a list [of list of list...] of numeric values 
np.array([[0, 1], [1, 0]], dtype=np.float32)

array([[0., 1.],
       [1., 0.]], dtype=float32)

In [25]:
np.zeros((4, 3), dtype=np.int64) # all values are 0

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [26]:
# Special constructors for special matrices
np.ones((3, 4)) # all values are 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
# An Identity Matrix. You will see that that this matrix is useful in Linear Algebra!
np.eye(3) # or np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Common constructors cont'd

Numerical ranges

In [28]:
np.arange(10) # from 0 to 10-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(2, 12) # from 2 to 12-1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
np.arange(2, 12, 0.5) # start, stop, step

array([ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,
        7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5])

In [31]:
np.linspace(0, 1, 5) # start, stop, num

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

(Pseudo)-random number generation

In [32]:
np.random.randint(10, size=(2, 2))  # 3x3 matrix with integers from 0 to 9

array([[4, 6],
       [9, 7]])

In [33]:
np.random.randn(2, 3) # 3x3 matrix with values extracted from a standard Gaussian

array([[-0.85252649, -1.36111031,  1.10335142],
       [ 0.76178578,  0.85093968,  0.02065152]])

In [34]:
np.random.rand(2, 5) # 2x2 matrix with random numbers extracted from the uniform distribution in [0, 1)

array([[0.69418405, 0.70726865, 0.01955149, 0.13984575, 0.77873465],
       [0.39166508, 0.70039219, 0.16535918, 0.14792574, 0.49242808]])

# Arithmetic with numpy


Basic operations ```+ - * /``` are available.

They are applied efficiently in a **vectorized** fashion, with the general objective of avoiding (slow) python ```for``` loops


* Operations between equal-size arrays are applied **element-wise**

In [35]:
res0 = np.ones((3, 3)) + np.eye(3) 
res0

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

* If one operand is scalar, it is repeated to match the dimension of the other operands

In [36]:
1/res0 # It is like: np.ones((3, 3))/res0

array([[0.5, 1. , 1. ],
       [1. , 0.5, 1. ],
       [1. , 1. , 0.5]])

 * More advanced [broadcasting rules](https://numpy.org/devdocs/user/theory.broadcasting.html) define behavior with arrays of different (but compatible) size.  They are out of the scope of this course

In [37]:
#np.random.randn(3, 3, 2) + np.random.randn(3, 2) # this works
#np.random.randn(3, 3, 2) + np.random.randn(3, 3, 1) # this works
#np.random.randn(3, 3, 2) + np.random.randn(3, 3) # this won't work

* Rationale: with a single line of code, instruct the computer to perform several useful operations. Then, the slow nature of Python becomes less critical.

# Universal functions

Perform the same operations on all elements multidimensional arrays. Universal in the sense that they can be applied to 1D, 2D, ... ND arrays.

Many universal functions are *unary* (i.e. they take one operand) and apply element-wise transformations

In [38]:
data = np.random.rand(2, 5)
data

array([[0.84737806, 0.08098227, 0.74297384, 0.0809275 , 0.88639351],
       [0.82462964, 0.51199849, 0.95018175, 0.56289649, 0.64108747]])

In [39]:
# Mathematical functions like sin, cos, tan, acos are implemented as unary universal functions
np.sin(data) # np.sin, np.cos, np.tan, np.acos, np.asin, np.exp, np.log, ...

array([[0.74954739, 0.08089379, 0.67648101, 0.08083919, 0.77479673],
       [0.73429642, 0.48992044, 0.81352121, 0.53363803, 0.59806734]])

Some universal funtions are *binary* (i.e. they take two operands of equal or compatible size)

In [40]:
x = np.random.randn(5)
y = np.random.randn(5)
print(x)
print(y)

[-0.75725126  2.16090004 -0.04830931 -0.92000793  0.91253702]
[-1.68875237 -0.70430012 -0.53838846  0.12644907  0.08513486]


In [41]:
# Maximum, minimum, power, ... are binary universal functions
z = np.maximum(x, y) #np.minimum, np.power, np.mod...
z

array([-0.75725126,  2.16090004, -0.04830931,  0.12644907,  0.91253702])

# Linear Algebra

All sort of linear algebra operations are available. Examples for vectors:

Let us construct the canonical base $\{\overrightarrow {e_1}, \overrightarrow {e_2}, \overrightarrow {e_3}\}$ of $\mathbb{R}^3$

In [42]:
# Canonical base of R^3. Note: e1, e2, e3 are 1D arrays, with 3 elements.
e1 = np.array([1, 0, 0]) 
e2 = np.array([0, 1, 0])
e3 = np.array([0, 0, 1])

Let us compute the dot product: $ \overrightarrow {e_1} \cdot \overrightarrow {e_2}$

In [43]:
np.dot(e1, e2) # dot product is zero (e1 and e2 are indeed perpendicular)

0

Let us compute the cross product: $ \overrightarrow {e_1} \times \overrightarrow {e_2}$

In [44]:
np.cross(e1, e2) # e1 x e2 = e3, as expected

array([0, 0, 1])

Let us compute $\overrightarrow {e_2} \times (3 \overrightarrow {e_2} + \overrightarrow {e_3} -2\overrightarrow {e_1})$

In [45]:
np.cross(e2, (3*e2 + e3 - 2*e1))

array([1, 0, 2])

No need to study Linear Algebra!

# Linear Algebra

All sort of linear algebra operations are available. Examples for matrices:

In [46]:
I2 = np.eye(2) # 2x2 identity matrix
A = np.random.randn(2, 2)
A

array([[0.08585941, 1.04626057],
       [0.39599101, 0.68176933]])

In [47]:
# This is a matrix multiplication
A @ I2 # or A.dot(I2)

array([[0.08585941, 1.04626057],
       [0.39599101, 0.68176933]])

In [48]:
# Warning: this is an element-wise multiplication!
A * I2

array([[0.08585941, 0.        ],
       [0.        , 0.68176933]])

In [49]:
np.linalg.det(A) # compute determinant of the matrix

-0.35577346973629304

In [50]:
b = np.random.randn(2)
b

array([-0.01163878,  0.23891333])

In [51]:
x = np.linalg.solve(A, b) # solve linear system Ax = b
x

array([ 0.72490103, -0.07061181])

In [52]:
A @ x # indeed, Ax = b!

array([-0.01163878,  0.23891333])

# Aggregations

Operations ''summarizing'' several numerical values to a scalar

In [53]:
A = np.random.randint(0, 4, size=(4, 2))
A

array([[2, 2],
       [2, 1],
       [3, 3],
       [2, 2]])

In [54]:
np.mean(A) # np.sum, np.max, np.min, np.std

2.125

We can optionally provide an ``axis`` parameter. Then, the aggregation is performed over that axis only.

In [55]:
np.mean(A, axis=0) # Aggregate over axis 0 (rows). Then, we are computing the mean of the 2 columns.

array([2.25, 2.  ])

In [56]:
np.mean(A, axis=1) # Aggregate over axis 1 (columns). Then, we are computing the mean of the 4 rows.

array([2. , 1.5, 3. , 2. ])

Note: for multi-dimensional arrays, ``axis`` may be a tuple of all the axes to be aggregated.

# Basic indexing

As lists, numpy ndarrays are indexed by integers starting from 0 and accessed using square brackets notation:

In [57]:
arr1d = np.arange(10) # 0, 1, 2, ..., 9
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr1d[2]

2

For multidimensional arrays, just use multiple indexes separated by commas:

In [59]:
I3 = np.eye(3) # 3x3 identity matrix
I3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
I3[1, 1] # elements on the diagonal are 1

1.0

In [61]:
I3[0, 1] # off-diagonal elements are 0

0.0

Numpy arrays are *mutable*:

In [62]:
I3[2, 2] = 2 # arrays are mutable
I3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 2.]])

# Slicing

Allows extracting a portion of an array. The general syntax is:
```python 
x[start:stop:step]
```

If any of these are unspecified, they default to start=0, stop=size of dimension, step=1. 

Slicing notation for 1D arrays is similar to the one for list:


In [63]:
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
arr1d[0:8] # start from 0, step=1, until index < 8. Thus, the last index is 7

array([0, 1, 2, 3, 4, 5, 6, 7])

In [65]:
arr1d[1:9:2] # start from 1, step=2, until index < 8. Thus, the last index is 7

array([1, 3, 5, 7])

In [66]:
arr1d[::-1] # reverse

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Negative indices refer to the end of the array

In [67]:
arr1d[2:-1] # start from index 2 and skip the last 1 element

array([2, 3, 4, 5, 6, 7, 8])

In [68]:
arr1d[1:-2] # start from index 1 and skip the last 2 element

array([1, 2, 3, 4, 5, 6, 7])

# Slicing cont'd

The notation extends naturally to multidimensional arrays

In [69]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
arr2d[1:, 1:]

array([[5, 6],
       [8, 9]])

Slicing can be combined with basic indexing

In [71]:
arr2d[0, :] # first row

array([1, 2, 3])

In [72]:
arr2d[:, 0] # first column

array([1, 4, 7])

# Boolean indexing

Refers to indexing through numpy arrays of booleans. Very useful in practice

In [73]:
data = np.random.randn(3, 4)
data

array([[ 1.22118371, -0.32867955, -1.33341563, -0.9057217 ],
       [ 0.05106508, -0.45226158, -0.01137966,  1.46082286],
       [ 0.05195674, -0.3488188 , -0.22328063, -0.5102558 ]])

In [74]:
mask = data < 0 # a numpy array of booleans (boolean mask)
mask

array([[False,  True,  True,  True],
       [False,  True,  True, False],
       [False,  True,  True,  True]])

In [75]:
arr = data[mask]
arr

array([-0.32867955, -1.33341563, -0.9057217 , -0.45226158, -0.01137966,
       -0.3488188 , -0.22328063, -0.5102558 ])

Boolean indexing is often used to modify array elements according to a logical condition:

In [76]:
data[data<0] = 0.0 # typical use: change values according to a logical condition
data

array([[1.22118371, 0.        , 0.        , 0.        ],
       [0.05106508, 0.        , 0.        , 1.46082286],
       [0.05195674, 0.        , 0.        , 0.        ]])

# Boolean indexing cont'd

More complex conditions can  be defined using the operators 

* Logical 'or' ``|``
* Logical 'and' ``&``
* Logical 'not' ``~``
* Equal `==`


In [77]:
data = np.random.randn(3, 4)
data

array([[-0.37937634,  0.43360672, -0.74302078, -2.24085338],
       [-0.20030868,  0.91621595,  0.28704724, -0.9563717 ],
       [ 0.22165996,  0.03991767,  0.67718736, -0.94526928]])

In [78]:
mask = (data < -0.6) | (data > 0.6) # a  logical condition using  the 'or' operator |
mask

array([[False, False,  True,  True],
       [False,  True, False,  True],
       [False, False,  True,  True]])

In [79]:
mask = (data > 0) & (data < 0.5) # a logical condition using the 'and' operator &
mask

array([[False,  True, False, False],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [80]:
data[mask] = data[mask] * 10
data[mask]

array([4.33606718, 2.87047245, 2.21659963, 0.39917666])

# Fancy indexing

Refers to indexing through an **array** (or a list) of integers 

In [81]:
data = np.random.randn(10, 3)
data

array([[ 0.86849182,  0.14631225, -1.3858273 ],
       [ 0.68825883,  0.72983383, -1.23117963],
       [-0.65196038,  0.45829283, -0.60527303],
       [ 0.20719083, -0.63581469, -0.39852595],
       [ 2.65145678, -0.44628034,  0.83864829],
       [ 2.08844104,  0.24245353,  0.40887664],
       [ 0.3068915 , -0.05428726, -0.98848254],
       [-1.85345917, -0.53164366,  1.20703257],
       [ 0.03406085, -1.03712201, -0.49109517],
       [ 0.38505494, -1.17610846,  0.49584305]])

In [82]:
data[[0, 1, 8, 9]] # select the rows 0, 1, 8, 9 of the matrix

array([[ 0.86849182,  0.14631225, -1.3858273 ],
       [ 0.68825883,  0.72983383, -1.23117963],
       [ 0.03406085, -1.03712201, -0.49109517],
       [ 0.38505494, -1.17610846,  0.49584305]])

If you provide multiple arrays, the behavior of fancy indexing is different:

In [83]:
data[[0, 1, 9], [1, 2, 0]] # select the elements in position (0,1), (1,2), (9,0)

array([ 0.14631225, -1.23117963,  0.38505494])

# Reshaping

View the data of an array as another array with different dimensions, but same number of elements.

In [84]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [85]:
A = x.reshape(4, 4)#, order="C")
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Note: the matrix A is filled "row by row". This is the default behavior in Python and corresponds to the  *row-major* convention adopted in C language. <br/> 

Other languages like FORTRAN or MATLAB fill matrices by column, according to the *column-major* convention. In numpy, this is forced using the ``order="F"`` option. 

In [86]:
A = x.reshape(4, 4, order="F") # order="C" or "F"
A

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In C, the elements on the same row are close in memory. In FORTRAN, the elements on the same column are close in memory!

# Reshaping cont'd

Let us create another view of our data:

In [87]:
B = x.reshape(2, 8)
B

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

We can now access and also modify the 2D array B

In [88]:
B[1, 7]

15

In [89]:
B[1, 7] = 100
B

array([[  0,   1,   2,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12,  13,  14, 100]])

**Warning**: x and B refer to *the same* memory! Thus, also x has been modified. Is this what we wanted?

In [90]:
x # the array x has also been modified!

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14, 100])

To create an *independent* data structure, use ``np.copy``

In [91]:
B_cpy = np.copy(B) # Further changes on B_cpy do not affect x as it refers to a different location in memory